package com.example.util

import android.content.Context
import android.content.SharedPreferences
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.getValue
import com.example.data.model.AppFeature
import com.example.data.model.PaymentMethodType
import com.example.data.model.SubscriptionTier
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

@Immutable
enum class AppLanguage(
    val code: String,
    val localeTag: String,
    val displayName: String,
    val flag: String
) {
    RU("ru", "ru-RU", "Русский", "🇷🇺"),
    UK("uk", "uk-UA", "Українська", "🇺🇦"),
    EN("en", "en-US", "English", "🇬🇧");

    companion object {
        fun fromCode(code: String?): AppLanguage {
            val normalized = code.orEmpty().trim().lowercase().replace('_', '-')
            return entries.firstOrNull { language ->
                normalized == language.code ||
                    normalized == language.localeTag.lowercase() ||
                    normalized.startsWith("${language.code}-")
            } ?: RU
        }
    }
}

enum class StringKey {
    // App & Tabs
    APP_NAME,
    TAB_DIARY,
    TAB_WEIGHT,
    TAB_FOODS,
    TAB_INSIGHTS,
    TAB_PROFILE,
    HEADER_PLANS_BTN,
    GUEST_ACCESS_FOREVER,
    GUEST_ACCESS_DAYS_LEFT,
    GUEST_ACCESS_ACTIVE_CODE,

    // Common
    SAVE,
    CANCEL,
    CLOSE,
    DELETE,
    EDIT,
    SEARCH,
    ADD,
    COPY,
    SHARE,
    LOADING,
    ERROR,
    SUCCESS,
    UNLOCKED,
    LOCKED,
    PRO_REQUIRED,
    PREMIUM_REQUIRED,
    ACTIVE_BADGE,

    // Language
    LANGUAGE_TITLE,
    SELECT_LANGUAGE,

    // Subscription & Tiers
    SUBSCRIPTION_TITLE,
    CURRENT_PLAN,
    PLAN_FREE,
    PLAN_SLIM,
    PLAN_PREMIUM,
    PLAN_ADMIN,
    FREE_PRICE,
    SLIM_PRICE,
    PREMIUM_PRICE,
    UPGRADE_PLAN,
    UNLOCK_ALL,
    PAYWALL_TITLE,
    PAYWALL_SUBTITLE,
    PAYWALL_FEATURE_LOCKED_FMT,
    PAYWALL_ALREADY_ACTIVE,
    PAYWALL_BUY_BTN_FMT,
    PAYWALL_SELECT_FREE,
    PAYWALL_HAVE_PROMO,
    PAYWALL_SECURITY_NOTE,
    CHOOSE_PLAN,
    POPULAR_CHOICE,
    BEST_VALUE,

    // Admin Panel
    ADMIN_PANEL_TITLE,
    ADMIN_PANEL_SUBTITLE,
    ADMIN_FILE_IMPORT_TITLE,
    ADMIN_FILE_IMPORT_DESC,
    ADMIN_IMPORT_BUTTON,
    ADMIN_EXPORT_BUTTON,
    ADMIN_RESET_BUTTON,
    ADMIN_TIER_SIMULATOR,
    ADMIN_CONFIG_STATUS,
    ADMIN_CONFIG_SOURCE_DEFAULT,
    ADMIN_CONFIG_SOURCE_FILE,
    ADMIN_CONFIG_UPDATED,
    ADMIN_VIEW_JSON,
    ADMIN_SUCCESS_IMPORT,
    ADMIN_ERROR_IMPORT,
    ADMIN_EXTRA_FOODS_IMPORTED,

    // Diary Screen
    DIARY_CALORIES_LEFT,
    DIARY_CONSUMED,
    DIARY_BURNED,
    DIARY_TARGET,
    DIARY_PROTEIN,
    DIARY_FAT,
    DIARY_CARBS,
    DIARY_MEAL_BREAKFAST,
    DIARY_MEAL_LUNCH,
    DIARY_MEAL_DINNER,
    DIARY_MEAL_SNACKS,
    DIARY_ADD_FOOD,
    DIARY_QUICK_CALORIES,
    DIARY_COPY_YESTERDAY,
    DIARY_FASTING_TIMER,
    DIARY_FASTING_START,
    DIARY_FASTING_STOP,
    DIARY_WATER_TRACKER,
    DIARY_ADD_EXERCISE,
    DIARY_BARCODE_SCANNER,

    // Weight Screen
    WEIGHT_TITLE,
    WEIGHT_CURRENT,
    WEIGHT_START,
    WEIGHT_TARGET,
    WEIGHT_TREND,
    WEIGHT_LOG_BUTTON,
    WEIGHT_CHART_TITLE,
    WEIGHT_MEASUREMENTS_TITLE,
    WEIGHT_WEEKLY_DEFICIT_TITLE,

    // Food Database
    FOOD_SEARCH_PLACEHOLDER,
    FOOD_ALL_CATEGORIES,
    FOOD_CREATE_CUSTOM,

    // Insights
    INSIGHTS_TITLE,
    INSIGHTS_STREAKS,
    INSIGHTS_WEEKLY_CHART,
    INSIGHTS_EXPORT_REPORT,

    // Profile Fields & Form
    PROFILE_TITLE,
    PROFILE_SUBTITLE,
    PROFILE_PERSONAL_DATA,
    PROFILE_GENDER,
    GENDER_MALE,
    GENDER_FEMALE,
    PROFILE_AGE,
    PROFILE_HEIGHT,
    PROFILE_START_WEIGHT,
    PROFILE_CURRENT_WEIGHT,
    PROFILE_TARGET_WEIGHT,
    PROFILE_ACTIVITY_LEVEL,
    PROFILE_GOAL_PACE,
    PROFILE_MACROS_TITLE,
    PROFILE_CALORIES_GOAL,
    PROFILE_PROTEIN_GOAL,
    PROFILE_FAT_GOAL,
    PROFILE_CARBS_GOAL,
    PROFILE_WATER_GOAL,
    PROFILE_AUTO_CALC,
    PROFILE_SAVE_SETTINGS,
    PROFILE_SAVED_SUCCESS,
    PROFILE_VALIDATION_FIX_ERRORS,
    PROFILE_ERROR_NAME_TOO_LONG,
    PROFILE_ERROR_ADULT_ONLY,
    PROFILE_ERROR_AGE_RANGE,
    PROFILE_ERROR_HEIGHT_RANGE,
    PROFILE_ERROR_WEIGHT_RANGE,
    PROFILE_ERROR_TARGET_ABOVE_CURRENT,
    PROFILE_ERROR_TARGET_TOO_LOW,
    PROFILE_ERROR_CALORIES_RANGE,
    PROFILE_ERROR_MACRO_RANGE,
    PROFILE_ERROR_WATER_RANGE,
    PROFILE_SAFE_CALC_NOTE,

    // Activity Levels
    ACTIVITY_SEDENTARY,
    ACTIVITY_SEDENTARY_DESC,
    ACTIVITY_LIGHT,
    ACTIVITY_LIGHT_DESC,
    ACTIVITY_MODERATE,
    ACTIVITY_MODERATE_DESC,
    ACTIVITY_ACTIVE,
    ACTIVITY_ACTIVE_DESC,

    // Goal Paces
    PACE_EASY,
    PACE_RECOMMENDED,
    PACE_FAST,
    PACE_MAX,

    // Body Analysis Result Card
    ANALYSIS_RESULT_TITLE,
    ANALYSIS_RESULT_SUBTITLE,
    ANALYSIS_BMI_LABEL,
    BMI_UNDERWEIGHT,
    BMI_NORMAL,
    BMI_OVERWEIGHT,
    BMI_OBESITY,
    ANALYSIS_IDEAL_WEIGHT_RANGE,
    ANALYSIS_DIFF_TO_GOAL,
    ANALYSIS_TO_LOSE,
    ANALYSIS_TO_GAIN,
    ANALYSIS_TDEE_LABEL,
    ANALYSIS_BMR_LABEL,
    ANALYSIS_WEEKS_ESTIMATE,
    ANALYSIS_HELP_BUTTON_TEXT,

    // Explainer Dialog (Pop-up with X)
    EXPLAINER_DIALOG_TITLE,
    EXPLAINER_SECTION_WHAT_IT_MEANS,
    EXPLAINER_SECTION_PROBLEMS,
    EXPLAINER_SECTION_HOW_TO_IMPROVE,
    EXPLAINER_SECTION_HOW_APP_HELPS,
    EXPLAINER_SECTION_MOTIVATION,
    EXPLAINER_GOT_IT_BUTTON,

    // Lead Magnet Banner & Tiers
    LEAD_MAGNET_TITLE,
    LEAD_MAGNET_SUBTITLE,
    LEAD_MAGNET_PERK_1,
    LEAD_MAGNET_PERK_2,
    LEAD_MAGNET_PERK_3,
    LEAD_MAGNET_BUTTON,

    // Diary extras
    DIARY_WATER_HINT,
    DIARY_EXERCISE_TITLE,
    DIARY_EXERCISE_HINT,
    DIARY_NO_ITEMS_YET,
    DIARY_HABITS_TITLE,
    DIARY_HABITS_DESC,
    DIARY_OPEN_HABITS,
    DIARY_CALORIES_OVER,
    DIARY_CURRENT_DEFICIT,
    DIARY_CURRENT_SURPLUS,
    DIARY_MACROS_TITLE,

    // Admin & In-App Update
    ADMIN_TAB_UPDATE,
    ADMIN_INSTALL_APK_BUTTON,
    ADMIN_INSTALL_APK_DESC,
    ADMIN_APK_NO_DELETE_NOTE,

    // Units
    UNIT_KCAL,
    UNIT_GRAM,
    UNIT_ML,
    UNIT_CM,
    UNIT_MIN,

    // Insights extra
    INSIGHTS_SUBTITLE,
    INSIGHTS_FASTING_TITLE,
    INSIGHTS_FASTING_ACTIVE,
    INSIGHTS_FASTING_STOPPED,
    INSIGHTS_FASTING_BTN_START,
    INSIGHTS_FASTING_BTN_STOP,
    INSIGHTS_RULES_TITLE,

    // Weight extra
    WEIGHT_HEADER_SUBTITLE,
    WEIGHT_ADD_BUTTON,
    WEIGHT_LOST_LABEL,
    WEIGHT_REMAINING_LABEL,
    WEIGHT_WEEKS_LABEL,
    WEIGHT_PROGRESS_TO_GOAL,
    WEIGHT_FORECAST_TEXT,
    WEIGHT_HISTORY_TITLE,
    WEIGHT_EMPTY_HISTORY,
    WEIGHT_UNIT_KG,

    // Chart & Trend & Weekly Deficit & Measurements & Habits & Export
    CHART_SUBTITLE,
    CHART_FILTER_7D,
    CHART_FILTER_30D,
    CHART_FILTER_ALL,
    CHART_EMPTY,
    CHART_ACTUAL_WEIGHT,
    TREND_CARD_TITLE,
    TREND_CARD_SUBTITLE,
    TREND_LABEL_TREND,
    TREND_LABEL_SCALE,
    TREND_INFO_GOOD,
    TREND_INFO_NORMAL,
    WEEKLY_DEFICIT_SUBTITLE,
    WEEKLY_FAT_BURN_FORECAST,
    WEEKLY_FAT_BURN_NOTE,
    MEAS_TITLE,
    MEAS_SUBTITLE,
    MEAS_WAIST,
    MEAS_HIPS,
    MEAS_CHEST,
    MEAS_BICEP,
    MEAS_THIGH,
    MEAS_ADD_BTN,
    MEAS_EMPTY_HINT,
    HABIT_STREAK_BADGE,
    HABIT_1,
    HABIT_2,
    HABIT_3,
    HABIT_4,
    HABIT_5,
    EXPORT_SUBTITLE,
    EXPORT_SHARE_BTN,
    EXPORT_COPY_BTN,
    EXPORT_COPIED_TOAST,

    // Dialogs (Add Food, Exercise, Weight, Quick Calories, Barcode, Promo, Payment, Receipt)
    DIALOG_ADD_FOOD_TITLE,
    DIALOG_GRAMS_LABEL,
    DIALOG_EMPTY_FOODS,
    DIALOG_ADD_EXERCISE_TITLE,
    DIALOG_EXERCISE_NAME_LABEL,
    DIALOG_EXERCISE_MINUTES_LABEL,
    DIALOG_EXERCISE_KCAL_LABEL,
    DIALOG_ADD_WEIGHT_TITLE,
    DIALOG_WEIGHT_INPUT_LABEL,
    DIALOG_NOTE_LABEL,
    DIALOG_QUICK_CALORIES_TITLE,
    DIALOG_QUICK_CALORIES_SUBTITLE,
    DIALOG_BARCODE_TITLE,
    DIALOG_BARCODE_SUBTITLE,
    DIALOG_BARCODE_INPUT_LABEL,
    DIALOG_BARCODE_CAMERA_HINT,
    DIALOG_BARCODE_CAMERA_PERMISSION,
    DIALOG_BARCODE_GRANT_PERMISSION,
    DIALOG_BARCODE_NOT_FOUND,
    DIALOG_BARCODE_SCAN_AGAIN,
    DIALOG_BARCODE_CAMERA_ERROR,
    DIALOG_BARCODE_MANUAL_HINT,
    DIALOG_BARCODE_SEARCHING,
    DIALOG_PROMO_TITLE,
    DIALOG_PROMO_SUBTITLE,
    DIALOG_PROMO_INPUT_LABEL,
    DIALOG_PROMO_ACTIVATE_BTN,
    DIALOG_PAYMENT_TITLE,
    DIALOG_PAYMENT_SELECT_METHOD,
    DIALOG_PAYMENT_REQUISITES_HEADER,
    DIALOG_PAYMENT_AMOUNT_TO_PAY,
    DIALOG_PAYMENT_NOTE_LABEL,
    DIALOG_PAYMENT_CONFIRM_BTN,
    DIALOG_PAYMENT_SECURITY_FOOTER,
    DIALOG_RECEIPT_TITLE,
    DIALOG_RECEIPT_SUBTITLE_FMT,
    DIALOG_RECEIPT_PENDING_BADGE,
    DIALOG_RECEIPT_ORDER_ID,
    DIALOG_RECEIPT_DATE,
    DIALOG_RECEIPT_METHOD,
    DIALOG_RECEIPT_TOTAL,
    DIALOG_RECEIPT_DONE_BTN,
    ADMIN_REQUISITES_HEADER,
    ADMIN_REQUISITES_SUBTITLE,
    ADMIN_REQUISITES_ENABLED_METHODS,
    ADMIN_REQUISITES_SAVE_BTN,
    ADMIN_REQUISITES_SAVED_TOAST,

    // Foods extra
    FOODS_TITLE,
    FOODS_SUBTITLE,
    FOODS_SEARCH_HINT,
    FOODS_CAT_ALL,
    FOODS_CAT_MEAT,
    FOODS_CAT_FISH,
    FOODS_CAT_GRAINS,
    FOODS_CAT_DAIRY,
    FOODS_CAT_VEG,
    FOODS_CAT_FRUITS,
    FOODS_CAT_SNACKS,
    FOODS_CREATE_BTN,
    FOOD_CUSTOM_BADGE,
    FOOD_NAME_LABEL,
    FOOD_CATEGORY_LABEL,
    FOOD_KCAL_100G_LABEL,

    // Admin extra
    ADMIN_TAB_FAMILY,
    ADMIN_TAB_REQUISITES,
    ADMIN_TAB_TIERS_JSON,
    ADMIN_FAMILY_TITLE,
    ADMIN_FAMILY_DESC,
    ADMIN_FAMILY_SHARE_BTN,
    ADMIN_COPY_CODE,
    ADMIN_QUICK_GUEST_LINKS,
    ADMIN_GUEST_SLIM_7D,
    ADMIN_GUEST_PREMIUM_7D,
    ADMIN_GUEST_PREMIUM_30D,
    ADMIN_SHARE_ACTION,
    ADMIN_CUSTOM_INVITE_CREATE,
    ADMIN_CUSTOM_INVITE_HIDE,
    ADMIN_ACTIVE_INVITES_LIST,
    ADMIN_DURATION_FOREVER,

    // Insights 5 Tips
    TIP_1_TITLE,
    TIP_1_SUBTITLE,
    TIP_1_CONTENT,
    TIP_2_TITLE,
    TIP_2_SUBTITLE,
    TIP_2_CONTENT,
    TIP_3_TITLE,
    TIP_3_SUBTITLE,
    TIP_3_CONTENT,
    TIP_4_TITLE,
    TIP_4_SUBTITLE,
    TIP_4_CONTENT,
    TIP_5_TITLE,
    TIP_5_SUBTITLE,
    TIP_5_CONTENT,

    // Profile extras
    PROFILE_SMART_CALC_TITLE,
    PROFILE_SMART_CALC_DESC,
    PROFILE_RECALC_BTN,
    PROFILE_CHANGE_PLAN_BTN,
    PROFILE_PAYMENT_BTN,
    PROFILE_PROMO_BTN,

    LANGUAGE_DROPDOWN_DESC,
    PROMO_ACTIVATION_HINT,
    PROMO_INVALID_CODE,
    ADMIN_PROMO_CODE_LABEL,
    ADMIN_SOURCE_LABEL,
    ADMIN_VERSION_LABEL,
    ADMIN_PAYMENT_SETTINGS_TITLE,
    ADMIN_PAYMENT_SETTINGS_DESC,
    ADMIN_PAYMENT_METHODS_ENABLED,
    ADMIN_PAYMENT_METHODS_HINT,
    ADMIN_MONOBANK_SECTION,
    ADMIN_MONOBANK_CARD_LABEL,
    ADMIN_MONOBANK_JAR_LABEL,
    ADMIN_PAYPAL_SECTION,
    ADMIN_PAYPAL_EMAIL_LABEL,
    ADMIN_PAYPAL_ME_LABEL,
    ADMIN_CRYPTO_SECTION,
    ADMIN_USDT_ADDRESS_LABEL,
    ADMIN_USDT_NETWORK_LABEL,
    ADMIN_BTC_ADDRESS_LABEL,
    ADMIN_BANK_SECTION,
    ADMIN_CARD_NUMBER_LABEL,
    ADMIN_CARD_HOLDER_LABEL,
    ADMIN_IBAN_LABEL,
    ADMIN_SUPPORT_CONTACTS,
    ADMIN_TELEGRAM_LABEL,
    ADMIN_SUPPORT_EMAIL_LABEL,
    ADMIN_PAYMENT_DETAILS_SAVED,
    ADMIN_SAVE_PAYMENT_DETAILS,
    SHARE_LABEL,
    COPY_LABEL
}

object LocalizationManager {
    private const val PREFS_NAME = "slimtrack_localization_prefs"
    private const val KEY_LANGUAGE = "selected_language_code"

    private lateinit var preferences: SharedPreferences
    private val _currentLanguage = MutableStateFlow(AppLanguage.RU)
    val currentLanguage: StateFlow<AppLanguage> = _currentLanguage.asStateFlow()

    fun init(context: Context) {
        preferences = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        val savedCode = preferences.getString(KEY_LANGUAGE, AppLanguage.RU.code) ?: AppLanguage.RU.code
        _currentLanguage.value = AppLanguage.fromCode(savedCode)
    }

    fun setLanguage(language: AppLanguage) {
        _currentLanguage.value = language
        if (::preferences.isInitialized) {
            preferences.edit().putString(KEY_LANGUAGE, language.code).apply()
        }
    }

    fun getString(key: StringKey, language: AppLanguage = _currentLanguage.value): String {
        return translations[language]?.get(key)
            ?: translations[AppLanguage.EN]?.get(key)
            ?: translations[AppLanguage.RU]?.get(key)
            ?: key.name
    }

    /** Used by tests/diagnostics to prevent partially translated releases. */
    fun missingTranslationKeys(language: AppLanguage): List<StringKey> =
        StringKey.entries.filterNot { key -> translations[language]?.containsKey(key) == true }

    private val translations: Map<AppLanguage, Map<StringKey, String>> = mapOf(
        AppLanguage.RU to mapOf(
            StringKey.APP_NAME to "SlimTrack",
            StringKey.TAB_DIARY to "Дневник",
            StringKey.TAB_WEIGHT to "Вес",
            StringKey.TAB_FOODS to "База",
            StringKey.TAB_INSIGHTS to "Советы",
            StringKey.TAB_PROFILE to "Профиль",
            StringKey.HEADER_PLANS_BTN to "Тарифы ⭐",
            StringKey.GUEST_ACCESS_FOREVER to "Бессрочно 👑",
            StringKey.GUEST_ACCESS_DAYS_LEFT to "Осталось дн.:",
            StringKey.GUEST_ACCESS_ACTIVE_CODE to "Активен • Код:",

            StringKey.SAVE to "Сохранить",
            StringKey.CANCEL to "Отмена",
            StringKey.CLOSE to "Закрыть",
            StringKey.DELETE to "Удалить",
            StringKey.EDIT to "Редактировать",
            StringKey.SEARCH to "Поиск",
            StringKey.ADD to "Добавить",
            StringKey.COPY to "Копировать",
            StringKey.SHARE to "Поделиться",
            StringKey.LOADING to "Загрузка...",
            StringKey.ERROR to "Ошибка",
            StringKey.SUCCESS to "Успешно",
            StringKey.UNLOCKED to "Доступно",
            StringKey.LOCKED to "Заблокировано",
            StringKey.PRO_REQUIRED to "Требуется Slim ($20)",
            StringKey.PREMIUM_REQUIRED to "Требуется Premium ($50)",
            StringKey.ACTIVE_BADGE to "Активен",

            StringKey.LANGUAGE_TITLE to "Язык приложения",
            StringKey.SELECT_LANGUAGE to "Выберите язык интерфейса",

            StringKey.SUBSCRIPTION_TITLE to "Тарифные планы",
            StringKey.CURRENT_PLAN to "Текущий тариф",
            StringKey.PLAN_FREE to "Free (Бесплатный)",
            StringKey.PLAN_SLIM to "Slim ($20)",
            StringKey.PLAN_PREMIUM to "Premium ($50)",
            StringKey.PLAN_ADMIN to "Администратор (VIP)",
            StringKey.FREE_PRICE to "$0",
            StringKey.SLIM_PRICE to "$20",
            StringKey.PREMIUM_PRICE to "$50",
            StringKey.UPGRADE_PLAN to "Улучшить тариф",
            StringKey.UNLOCK_ALL to "Открыть все функции",
            StringKey.PAYWALL_TITLE to "Все возможности SlimTrack",
            StringKey.PAYWALL_SUBTITLE to "Выберите подходящий тариф для быстрого и комфортного снижения веса",
            StringKey.PAYWALL_FEATURE_LOCKED_FMT to "Функция доступна в тарифе",
            StringKey.PAYWALL_ALREADY_ACTIVE to "Тариф уже активен ✓",
            StringKey.PAYWALL_BUY_BTN_FMT to "Оплатить",
            StringKey.PAYWALL_SELECT_FREE to "Выбрать бесплатный тариф",
            StringKey.PAYWALL_HAVE_PROMO to "🎁 Есть промокод или гостевая ссылка?",
            StringKey.PAYWALL_SECURITY_NOTE to "🔒 Мгновенная активация и выдача квитанции",
            StringKey.CHOOSE_PLAN to "Выбрать тариф",
            StringKey.POPULAR_CHOICE to "Популярный 🔥",
            StringKey.BEST_VALUE to "VIP 👑",

            StringKey.ADMIN_PANEL_TITLE to "Панель администратора",
            StringKey.ADMIN_PANEL_SUBTITLE to "Управление доступом, оплатой и обновлениями",
            StringKey.ADMIN_FILE_IMPORT_TITLE to "Импорт файла конфигурации (.json)",
            StringKey.ADMIN_FILE_IMPORT_DESC to "Загрузите JSON-файл для обновления тарифов или базы продуктов",
            StringKey.ADMIN_IMPORT_BUTTON to "Загрузить .JSON",
            StringKey.ADMIN_EXPORT_BUTTON to "Копировать JSON",
            StringKey.ADMIN_RESET_BUTTON to "Сброс настроек",
            StringKey.ADMIN_TIER_SIMULATOR to "Тестовый симулятор тарифа",
            StringKey.ADMIN_CONFIG_STATUS to "Статус конфигурации",
            StringKey.ADMIN_CONFIG_SOURCE_DEFAULT to "Встроенная",
            StringKey.ADMIN_CONFIG_SOURCE_FILE to "Из файла",
            StringKey.ADMIN_CONFIG_UPDATED to "Обновлено",
            StringKey.ADMIN_VIEW_JSON to "Показать JSON",
            StringKey.ADMIN_SUCCESS_IMPORT to "Конфигурация успешно применена!",
            StringKey.ADMIN_ERROR_IMPORT to "Ошибка чтения файла конфигурации",
            StringKey.ADMIN_EXTRA_FOODS_IMPORTED to "Импортировано продуктов",

            StringKey.DIARY_CALORIES_LEFT to "Осталось",
            StringKey.DIARY_CONSUMED to "Съедено",
            StringKey.DIARY_BURNED to "Сожжено",
            StringKey.DIARY_TARGET to "Норма",
            StringKey.DIARY_PROTEIN to "Белки",
            StringKey.DIARY_FAT to "Жиры",
            StringKey.DIARY_CARBS to "Углеводы",
            StringKey.DIARY_MEAL_BREAKFAST to "Завтрак",
            StringKey.DIARY_MEAL_LUNCH to "Обед",
            StringKey.DIARY_MEAL_DINNER to "Ужин",
            StringKey.DIARY_MEAL_SNACKS to "Перекус",
            StringKey.DIARY_ADD_FOOD to "Добавить",
            StringKey.DIARY_QUICK_CALORIES to "Быстрые ккал",
            StringKey.DIARY_COPY_YESTERDAY to "Вчерашнее",
            StringKey.DIARY_FASTING_TIMER to "Интервальное голодание",
            StringKey.DIARY_FASTING_START to "Старт",
            StringKey.DIARY_FASTING_STOP to "Стоп",
            StringKey.DIARY_WATER_TRACKER to "Трекер воды",
            StringKey.DIARY_ADD_EXERCISE to "Активность",
            StringKey.DIARY_BARCODE_SCANNER to "Штрих-код",

            StringKey.WEIGHT_TITLE to "Динамика веса",
            StringKey.WEIGHT_CURRENT to "Текущий",
            StringKey.WEIGHT_START to "Старт",
            StringKey.WEIGHT_TARGET to "Цель",
            StringKey.WEIGHT_TREND to "Трендовый вес",
            StringKey.WEIGHT_LOG_BUTTON to "Записать вес",
            StringKey.WEIGHT_CHART_TITLE to "График изменения веса",
            StringKey.WEIGHT_MEASUREMENTS_TITLE to "Замеры тела",
            StringKey.WEIGHT_WEEKLY_DEFICIT_TITLE to "Недельный дефицит калорий",

            StringKey.FOOD_SEARCH_PLACEHOLDER to "Поиск продуктов по названию...",
            StringKey.FOOD_ALL_CATEGORIES to "Все категории",
            StringKey.FOOD_CREATE_CUSTOM to "Создать продукт",

            StringKey.INSIGHTS_TITLE to "Аналитика и советы",
            StringKey.INSIGHTS_STREAKS to "Трекер привычек",
            StringKey.INSIGHTS_WEEKLY_CHART to "Баланс за 7 дней",
            StringKey.INSIGHTS_EXPORT_REPORT to "Экспорт отчета для тренера / врача",

            StringKey.PROFILE_TITLE to "Профиль и параметры",
            StringKey.PROFILE_SUBTITLE to "Персональный расчет дефицита калорий",
            StringKey.PROFILE_PERSONAL_DATA to "Личные параметры тела",
            StringKey.PROFILE_GENDER to "Пол",
            StringKey.GENDER_MALE to "Мужской",
            StringKey.GENDER_FEMALE to "Женский",
            StringKey.PROFILE_AGE to "Возраст (лет)",
            StringKey.PROFILE_HEIGHT to "Рост (см)",
            StringKey.PROFILE_START_WEIGHT to "Начальный вес (кг)",
            StringKey.PROFILE_CURRENT_WEIGHT to "Текущий вес (кг)",
            StringKey.PROFILE_TARGET_WEIGHT to "Желаемый вес (кг)",
            StringKey.PROFILE_ACTIVITY_LEVEL to "Образ жизни и подвижность",
            StringKey.PROFILE_GOAL_PACE to "Желаемый темп похудения",
            StringKey.PROFILE_MACROS_TITLE to "Дневные нормы питания (БЖУ)",
            StringKey.PROFILE_CALORIES_GOAL to "Цель калорий (ккал)",
            StringKey.PROFILE_PROTEIN_GOAL to "Белки (г)",
            StringKey.PROFILE_FAT_GOAL to "Жиры (г)",
            StringKey.PROFILE_CARBS_GOAL to "Углеводы (г)",
            StringKey.PROFILE_WATER_GOAL to "Норма воды (мл)",
            StringKey.PROFILE_AUTO_CALC to "Пересчитать нормы",
            StringKey.PROFILE_SAVE_SETTINGS to "Сохранить параметры",
            StringKey.PROFILE_SAVED_SUCCESS to "Параметры сохранены! ✓",
            StringKey.PROFILE_VALIDATION_FIX_ERRORS to "Проверьте выделенные поля перед сохранением.",
            StringKey.PROFILE_ERROR_NAME_TOO_LONG to "Имя слишком длинное.",
            StringKey.PROFILE_ERROR_ADULT_ONLY to "Автоматические расчёты SlimTrack доступны только для пользователей 18+.",
            StringKey.PROFILE_ERROR_AGE_RANGE to "Введите возраст от 18 до 100 лет.",
            StringKey.PROFILE_ERROR_HEIGHT_RANGE to "Введите рост от 120 до 230 см.",
            StringKey.PROFILE_ERROR_WEIGHT_RANGE to "Введите вес от 30 до 250 кг.",
            StringKey.PROFILE_ERROR_TARGET_ABOVE_CURRENT to "Для режима снижения веса цель не должна быть выше текущего веса.",
            StringKey.PROFILE_ERROR_TARGET_TOO_LOW to "Эта цель выходит за поддерживаемый диапазон для самостоятельного снижения веса.",
            StringKey.PROFILE_ERROR_CALORIES_RANGE to "Введите поддерживаемую дневную цель калорий.",
            StringKey.PROFILE_ERROR_MACRO_RANGE to "Введите поддерживаемое значение макронутриента.",
            StringKey.PROFILE_ERROR_WATER_RANGE to "Введите цель воды от 500 до 6000 мл.",
            StringKey.PROFILE_SAFE_CALC_NOTE to "Авторасчёт работает только для взрослых и ограничивает чрезмерный дефицит.",

            StringKey.ACTIVITY_SEDENTARY to "Сидячий образ жизни",
            StringKey.ACTIVITY_SEDENTARY_DESC to "Офисная работа, мало движений",
            StringKey.ACTIVITY_LIGHT to "Легкая активность",
            StringKey.ACTIVITY_LIGHT_DESC to "Тренировки или ходьба 1–3 раза в неделю",
            StringKey.ACTIVITY_MODERATE to "Умеренная активность",
            StringKey.ACTIVITY_MODERATE_DESC to "Спорт 3–5 раз в неделю",
            StringKey.ACTIVITY_ACTIVE to "Высокая активность",
            StringKey.ACTIVITY_ACTIVE_DESC to "Интенсивный спорт 6–7 раз в неделю",

            StringKey.PACE_EASY to "Мягкий (-0.25 кг/нед)",
            StringKey.PACE_RECOMMENDED to "Оптимальный (-0.5 кг/нед)",
            StringKey.PACE_FAST to "Быстрый (-0.75 кг/нед)",
            StringKey.PACE_MAX to "Максимум (-1.0 кг/нед)",

            StringKey.ANALYSIS_RESULT_TITLE to "Анализ параметров тела",
            StringKey.ANALYSIS_RESULT_SUBTITLE to "Расчет ИМТ, расхода калорий и сроков цели",
            StringKey.ANALYSIS_BMI_LABEL to "Индекс массы тела (ИМТ)",
            StringKey.BMI_UNDERWEIGHT to "Дефицит массы",
            StringKey.BMI_NORMAL to "Норма веса ✓",
            StringKey.BMI_OVERWEIGHT to "Избыточный вес",
            StringKey.BMI_OBESITY to "Ожирение",
            StringKey.ANALYSIS_IDEAL_WEIGHT_RANGE to "Здоровый вес",
            StringKey.ANALYSIS_DIFF_TO_GOAL to "До цели",
            StringKey.ANALYSIS_TO_LOSE to "Сбросить",
            StringKey.ANALYSIS_TO_GAIN to "Набрать",
            StringKey.ANALYSIS_TDEE_LABEL to "Суточный расход (TDEE)",
            StringKey.ANALYSIS_BMR_LABEL to "Базовый обмен (BMR)",
            StringKey.ANALYSIS_WEEKS_ESTIMATE to "Прогноз срока",
            StringKey.ANALYSIS_HELP_BUTTON_TEXT to "Разбор ❔",

            StringKey.EXPLAINER_DIALOG_TITLE to "Разбор ваших параметров",
            StringKey.EXPLAINER_SECTION_WHAT_IT_MEANS to "1. Что означают показатели",
            StringKey.EXPLAINER_SECTION_PROBLEMS to "2. На что это влияет",
            StringKey.EXPLAINER_SECTION_HOW_TO_IMPROVE to "3. Как улучшить результат",
            StringKey.EXPLAINER_SECTION_HOW_APP_HELPS to "4. Как помогает SlimTrack",
            StringKey.EXPLAINER_SECTION_MOTIVATION to "5. Мотивация",
            StringKey.EXPLAINER_GOT_IT_BUTTON to "Понятно, к цели! ✓",

            StringKey.LEAD_MAGNET_TITLE to "Откройте 100% возможностей PRO",
            StringKey.LEAD_MAGNET_SUBTITLE to "Сканер штрих-кодов, разбор тела, фастинг и авто-БЖУ",
            StringKey.LEAD_MAGNET_PERK_1 to "Сканер штрих-кодов и быстрый ввод калорий",
            StringKey.LEAD_MAGNET_PERK_2 to "Медицинский разбор ИМТ и прогноз в неделях",
            StringKey.LEAD_MAGNET_PERK_3 to "Таймер голодания 16:8 и экспорт отчетов",
            StringKey.LEAD_MAGNET_BUTTON to "Тарифы и скидки ⭐",

            StringKey.DIARY_WATER_HINT to "Ускоряет обмен веществ",
            StringKey.DIARY_EXERCISE_TITLE to "Активность и спорт",
            StringKey.DIARY_EXERCISE_HINT to "Увеличивает лимит калорий",
            StringKey.DIARY_NO_ITEMS_YET to "Нет записей",
            StringKey.DIARY_HABITS_TITLE to "Трекер привычек",
            StringKey.DIARY_HABITS_DESC to "Ежедневный чек-лист дисциплины",
            StringKey.DIARY_OPEN_HABITS to "Открыть",
            StringKey.DIARY_CALORIES_OVER to "превышено",
            StringKey.DIARY_CURRENT_DEFICIT to "Дефицит:",
            StringKey.DIARY_CURRENT_SURPLUS to "Профицит:",
            StringKey.DIARY_MACROS_TITLE to "Макронутриенты (БЖУ)",

            StringKey.ADMIN_TAB_UPDATE to "Обновление (.APK)",
            StringKey.ADMIN_INSTALL_APK_BUTTON to "Установить обновление (.apk)",
            StringKey.ADMIN_INSTALL_APK_DESC to "Выберите скачанный APK для обновления поверх без потери данных",
            StringKey.ADMIN_APK_NO_DELETE_NOTE to "💡 Удалять приложение не нужно! Android обновит его поверх и сохранит все записи.",

            StringKey.UNIT_KCAL to "ккал",
            StringKey.UNIT_GRAM to "г",
            StringKey.UNIT_ML to "мл",
            StringKey.UNIT_CM to "см",
            StringKey.UNIT_MIN to "мин",

            StringKey.INSIGHTS_SUBTITLE to "Научный подход к снижению веса",
            StringKey.INSIGHTS_FASTING_TITLE to "Интервальное голодание 16:8",
            StringKey.INSIGHTS_FASTING_ACTIVE to "Фаза активного голодания",
            StringKey.INSIGHTS_FASTING_STOPPED to "Таймер остановлен",
            StringKey.INSIGHTS_FASTING_BTN_START to "Старт",
            StringKey.INSIGHTS_FASTING_BTN_STOP to "Стоп",
            StringKey.INSIGHTS_RULES_TITLE to "5 правил устойчивого похудения",

            StringKey.WEIGHT_HEADER_SUBTITLE to "Контроль массы тела и объемов",
            StringKey.WEIGHT_ADD_BUTTON to "Записать вес",
            StringKey.WEIGHT_LOST_LABEL to "Сброшено",
            StringKey.WEIGHT_REMAINING_LABEL to "До цели",
            StringKey.WEIGHT_WEEKS_LABEL to "Недель",
            StringKey.WEIGHT_PROGRESS_TO_GOAL to "Прогресс к цели",
            StringKey.WEIGHT_FORECAST_TEXT to "Прогноз до цели: ≈",
            StringKey.WEIGHT_HISTORY_TITLE to "История взвешиваний",
            StringKey.WEIGHT_EMPTY_HISTORY to "Нет записей. Нажмите «Записать вес»!",
            StringKey.WEIGHT_UNIT_KG to "кг",

            StringKey.CHART_SUBTITLE to "Динамика массы тела",
            StringKey.CHART_FILTER_7D to "7 дн.",
            StringKey.CHART_FILTER_30D to "30 дн.",
            StringKey.CHART_FILTER_ALL to "Все",
            StringKey.CHART_EMPTY to "Нет данных. Запишите свой вес!",
            StringKey.CHART_ACTUAL_WEIGHT to "Вес",
            StringKey.TREND_CARD_TITLE to "Трендовый вес",
            StringKey.TREND_CARD_SUBTITLE to "Сглаженная линия без скачков воды",
            StringKey.TREND_LABEL_TREND to "Тренд",
            StringKey.TREND_LABEL_SCALE to "На весах",
            StringKey.TREND_INFO_GOOD to "Задержка воды скрывает отвес — сжигание жира идет по плану!",
            StringKey.TREND_INFO_NORMAL to "Вес стабильно снижается благодаря дефициту калорий.",
            StringKey.WEEKLY_DEFICIT_SUBTITLE to "Суммарный баланс за 7 дней",
            StringKey.WEEKLY_FAT_BURN_FORECAST to "Сжигание жира за неделю: ≈",
            StringKey.WEEKLY_FAT_BURN_NOTE to "7 700 ккал дефицита = 1 кг жировой ткани",
            StringKey.MEAS_TITLE to "Замеры объемов тела",
            StringKey.MEAS_SUBTITLE to "Объемы в сантиметрах",
            StringKey.MEAS_WAIST to "Талия",
            StringKey.MEAS_HIPS to "Бедра",
            StringKey.MEAS_CHEST to "Грудь",
            StringKey.MEAS_BICEP to "Бицепс",
            StringKey.MEAS_THIGH to "Бедро",
            StringKey.MEAS_ADD_BTN to "Записать",
            StringKey.MEAS_EMPTY_HINT to "Запишите объемы талии и бедер для контроля прогресса",
            StringKey.HABIT_STREAK_BADGE to "дн. подряд",
            StringKey.HABIT_1 to "Выпить дневную норму воды",
            StringKey.HABIT_2 to "Выполнить норму по белку",
            StringKey.HABIT_3 to "Уложиться в дефицит калорий",
            StringKey.HABIT_4 to "Минимум 8 000 шагов / спорт",
            StringKey.HABIT_5 to "Без еды за 3 часа до сна",
            StringKey.EXPORT_SUBTITLE to "Сводка прогресса по весу и КБЖУ",
            StringKey.EXPORT_SHARE_BTN to "Поделиться",
            StringKey.EXPORT_COPY_BTN to "Копировать",
            StringKey.EXPORT_COPIED_TOAST to "Отчет скопирован!",

            StringKey.DIALOG_ADD_FOOD_TITLE to "Добавить в",
            StringKey.DIALOG_GRAMS_LABEL to "Вес порции (г)",
            StringKey.DIALOG_EMPTY_FOODS to "Продукты не найдены",
            StringKey.DIALOG_ADD_EXERCISE_TITLE to "Добавить активность",
            StringKey.DIALOG_EXERCISE_NAME_LABEL to "Название тренировки",
            StringKey.DIALOG_EXERCISE_MINUTES_LABEL to "Длительность (мин)",
            StringKey.DIALOG_EXERCISE_KCAL_LABEL to "Сожжено (ккал)",
            StringKey.DIALOG_ADD_WEIGHT_TITLE to "Записать вес",
            StringKey.DIALOG_WEIGHT_INPUT_LABEL to "Ваш вес (кг)",
            StringKey.DIALOG_NOTE_LABEL to "Заметка (необязательно)",
            StringKey.DIALOG_QUICK_CALORIES_TITLE to "Быстрые калории",
            StringKey.DIALOG_QUICK_CALORIES_SUBTITLE to "Мгновенный ввод калорий без поиска блюда",
            StringKey.DIALOG_BARCODE_TITLE to "Сканер штрих-кода",
            StringKey.DIALOG_BARCODE_SUBTITLE to "Наведите камеру на штрих-код EAN/UPC или введите код вручную",
            StringKey.DIALOG_BARCODE_INPUT_LABEL to "Штрих-код",
            StringKey.DIALOG_BARCODE_CAMERA_HINT to "Поместите штрих-код в рамку",
            StringKey.DIALOG_BARCODE_CAMERA_PERMISSION to "Для сканирования нужен доступ к камере. Штрих-коды обрабатываются на устройстве.",
            StringKey.DIALOG_BARCODE_GRANT_PERMISSION to "Разрешить камеру",
            StringKey.DIALOG_BARCODE_NOT_FOUND to "Штрих-код считан, но товар не найден в локальной и онлайн-базе. Его можно добавить вручную.",
            StringKey.DIALOG_BARCODE_SCAN_AGAIN to "Сканировать снова",
            StringKey.DIALOG_BARCODE_CAMERA_ERROR to "Не удалось запустить камеру. Можно ввести код вручную.",
            StringKey.DIALOG_BARCODE_MANUAL_HINT to "Или введите код вручную",
            StringKey.DIALOG_BARCODE_SEARCHING to "Ищем продукт в локальной и онлайн-базе…",
            StringKey.DIALOG_PROMO_TITLE to "Промокод или ссылка",
            StringKey.DIALOG_PROMO_SUBTITLE to "Введите код доступа для активации Slim / Premium",
            StringKey.DIALOG_PROMO_INPUT_LABEL to "Промокод или ссылка",
            StringKey.DIALOG_PROMO_ACTIVATE_BTN to "Активировать доступ ✓",
            StringKey.DIALOG_PAYMENT_TITLE to "Оплата подписки",
            StringKey.DIALOG_PAYMENT_SELECT_METHOD to "Выберите способ оплаты:",
            StringKey.DIALOG_PAYMENT_REQUISITES_HEADER to "Реквизиты для перевода:",
            StringKey.DIALOG_PAYMENT_AMOUNT_TO_PAY to "Сумма к оплате:",
            StringKey.DIALOG_PAYMENT_NOTE_LABEL to "Примечание / Фамилия / TXID",
            StringKey.DIALOG_PAYMENT_CONFIRM_BTN to "Я оплатил(а) — Создать заявку на проверку",
            StringKey.DIALOG_PAYMENT_SECURITY_FOOTER to "🔒 Доступ активируется только после подтверждения оплаты",
            StringKey.DIALOG_RECEIPT_TITLE to "Заявка на проверку создана",
            StringKey.DIALOG_RECEIPT_SUBTITLE_FMT to "Отправьте заявку в поддержку. Доступ пока не активирован",
            StringKey.DIALOG_RECEIPT_PENDING_BADGE to "НА ПРОВЕРКЕ",
            StringKey.DIALOG_RECEIPT_ORDER_ID to "Номер заказа:",
            StringKey.DIALOG_RECEIPT_DATE to "Дата и время:",
            StringKey.DIALOG_RECEIPT_METHOD to "Способ оплаты:",
            StringKey.DIALOG_RECEIPT_TOTAL to "Итого:",
            StringKey.DIALOG_RECEIPT_DONE_BTN to "Готово",
            StringKey.ADMIN_REQUISITES_HEADER to "⚙️ Настройка реквизитов оплаты",
            StringKey.ADMIN_REQUISITES_SUBTITLE to "Укажите ваши карты и кошельки для приема оплаты",
            StringKey.ADMIN_REQUISITES_ENABLED_METHODS to "Включенные способы оплаты:",
            StringKey.ADMIN_REQUISITES_SAVE_BTN to "Сохранить реквизиты ✓",
            StringKey.ADMIN_REQUISITES_SAVED_TOAST to "Реквизиты сохранены!",

            StringKey.FOODS_TITLE to "База продуктов",
            StringKey.FOODS_SUBTITLE to "Калорийность и БЖУ на 100 г",
            StringKey.FOODS_SEARCH_HINT to "Поиск продуктов...",
            StringKey.FOODS_CAT_ALL to "Все",
            StringKey.FOODS_CAT_MEAT to "Мясо и птица",
            StringKey.FOODS_CAT_FISH to "Рыба",
            StringKey.FOODS_CAT_GRAINS to "Крупы",
            StringKey.FOODS_CAT_DAIRY to "Молочные продукты",
            StringKey.FOODS_CAT_VEG to "Овощи",
            StringKey.FOODS_CAT_FRUITS to "Фрукты",
            StringKey.FOODS_CAT_SNACKS to "Орехи и снеки",
            StringKey.FOODS_CREATE_BTN to "Свой продукт",
            StringKey.FOOD_CUSTOM_BADGE to "Свой",
            StringKey.FOOD_NAME_LABEL to "Название продукта",
            StringKey.FOOD_CATEGORY_LABEL to "Категория",
            StringKey.FOOD_KCAL_100G_LABEL to "Ккал на 100 г",

            StringKey.ADMIN_TAB_FAMILY to "Семья & Гости",
            StringKey.ADMIN_TAB_REQUISITES to "Реквизиты",
            StringKey.ADMIN_TAB_TIERS_JSON to "Тарифы & JSON",
            StringKey.ADMIN_FAMILY_TITLE to "Семейный VIP доступ НАВСЕГДА 👑",
            StringKey.ADMIN_FAMILY_DESC to "Бессрочный доступ ко всем функциям для близких",
            StringKey.ADMIN_FAMILY_SHARE_BTN to "Отправить семье",
            StringKey.ADMIN_COPY_CODE to "Код",
            StringKey.ADMIN_QUICK_GUEST_LINKS to "Быстрые гостевые инвайты:",
            StringKey.ADMIN_GUEST_SLIM_7D to "Гостевой Slim (7 дней)",
            StringKey.ADMIN_GUEST_PREMIUM_7D to "Пробный Premium (7 дней)",
            StringKey.ADMIN_GUEST_PREMIUM_30D to "Полный Premium (30 дней)",
            StringKey.ADMIN_SHARE_ACTION to "Поделиться",
            StringKey.ADMIN_CUSTOM_INVITE_CREATE to "Создать свой промокод",
            StringKey.ADMIN_CUSTOM_INVITE_HIDE to "Скрыть конструктор",
            StringKey.ADMIN_ACTIVE_INVITES_LIST to "Активные коды",
            StringKey.ADMIN_DURATION_FOREVER to "Бессрочно 👑",

            StringKey.TIP_1_TITLE to "1. Дефицит калорий — основа",
            StringKey.TIP_1_SUBTITLE to "Закон энергетического баланса",
            StringKey.TIP_1_CONTENT to "Расходуйте на 400–500 ккал больше, чем потребляете. Это обеспечивает стабильное сжигание жира без голодовок и срывов.",
            StringKey.TIP_2_TITLE to "2. Белок защищает мышцы",
            StringKey.TIP_2_SUBTITLE to "Норма: 1.6 – 2.0 г на 1 кг веса",
            StringKey.TIP_2_CONTENT to "Белковая пища (птица, рыба, яйца, творог) сохраняет мышцы при похудении и надолго устраняет чувство голода.",
            StringKey.TIP_3_TITLE to "3. Вода и колебания веса",
            StringKey.TIP_3_SUBTITLE to "Почему вес меняется за сутки",
            StringKey.TIP_3_CONTENT to "Соль и углеводы временно задерживают воду. Пейте 30 мл воды на 1 кг веса для снятия отеков и высокого метаболизма.",
            StringKey.TIP_4_TITLE to "4. Бытовая активность (NEAT)",
            StringKey.TIP_4_SUBTITLE to "Шаги важнее редких тренировок",
            StringKey.TIP_4_CONTENT to "8 000 – 10 000 шагов в день сжигают до 400 ккал без усталости центральной нервной системы и роста аппетита.",
            StringKey.TIP_5_TITLE to "5. Как пройти плато веса",
            StringKey.TIP_5_SUBTITLE to "Если вес стоит 2 недели",
            StringKey.TIP_5_CONTENT to "Учитывайте масла и соусы, следите за замерами талии в сантиметрах и спите не менее 7–8 часов.",

            StringKey.PROFILE_SMART_CALC_TITLE to "Авто-расчет по формуле",
            StringKey.PROFILE_SMART_CALC_DESC to "Формула Миффлина-Сан Жеора под ваш вес",
            StringKey.PROFILE_RECALC_BTN to "Рассчитать",
            StringKey.PROFILE_CHANGE_PLAN_BTN to "Тарифы",
            StringKey.PROFILE_PAYMENT_BTN to "Оплата",
            StringKey.PROFILE_PROMO_BTN to "Промокод",
            StringKey.LANGUAGE_DROPDOWN_DESC to "Список языков",
            StringKey.PROMO_ACTIVATION_HINT to "Введите промокод или гостевую ссылку для активации Slim или Premium",
            StringKey.PROMO_INVALID_CODE to "Неверный код",
            StringKey.ADMIN_PROMO_CODE_LABEL to "Промокод (VIP-FRIEND)",
            StringKey.ADMIN_SOURCE_LABEL to "Источник:",
            StringKey.ADMIN_VERSION_LABEL to "Версия:",
            StringKey.ADMIN_PAYMENT_SETTINGS_TITLE to "⚙️ Настройка платежей",
            StringKey.ADMIN_PAYMENT_SETTINGS_DESC to "Задайте реквизиты для ручной оплаты подписки. Доступ активируется только после подтвержденной проверки платежа.",
            StringKey.ADMIN_PAYMENT_METHODS_ENABLED to "Включенные способы оплаты:",
            StringKey.ADMIN_PAYMENT_METHODS_HINT to "Отключите ненужные способы оплаты, чтобы показывать пользователю только актуальные варианты.",
            StringKey.ADMIN_MONOBANK_SECTION to "Monobank (Украина 🇺🇦)",
            StringKey.ADMIN_MONOBANK_CARD_LABEL to "Номер карты Monobank",
            StringKey.ADMIN_MONOBANK_JAR_LABEL to "Ссылка на банку Monobank",
            StringKey.ADMIN_PAYPAL_SECTION to "PayPal (международные платежи 🌐)",
            StringKey.ADMIN_PAYPAL_EMAIL_LABEL to "Email аккаунта PayPal",
            StringKey.ADMIN_PAYPAL_ME_LABEL to "Ссылка PayPal.Me",
            StringKey.ADMIN_CRYPTO_SECTION to "Криптовалюта (USDT и Bitcoin)",
            StringKey.ADMIN_USDT_ADDRESS_LABEL to "Адрес кошелька USDT",
            StringKey.ADMIN_USDT_NETWORK_LABEL to "Сеть USDT (TRC-20, BEP-20, ERC-20)",
            StringKey.ADMIN_BTC_ADDRESS_LABEL to "Адрес кошелька Bitcoin (BTC)",
            StringKey.ADMIN_BANK_SECTION to "Банковская карта и IBAN",
            StringKey.ADMIN_CARD_NUMBER_LABEL to "Номер карты Visa / MasterCard",
            StringKey.ADMIN_CARD_HOLDER_LABEL to "Имя владельца карты латиницей",
            StringKey.ADMIN_IBAN_LABEL to "Расчетный счет IBAN",
            StringKey.ADMIN_SUPPORT_CONTACTS to "Контакты поддержки для платежей",
            StringKey.ADMIN_TELEGRAM_LABEL to "Telegram поддержки",
            StringKey.ADMIN_SUPPORT_EMAIL_LABEL to "Email поддержки",
            StringKey.ADMIN_PAYMENT_DETAILS_SAVED to "Реквизиты оплаты сохранены",
            StringKey.ADMIN_SAVE_PAYMENT_DETAILS to "Сохранить реквизиты оплаты ✓",
            StringKey.SHARE_LABEL to "Поделиться",
            StringKey.COPY_LABEL to "Копировать"
        ),

        AppLanguage.UK to mapOf(
            StringKey.APP_NAME to "SlimTrack",
            StringKey.TAB_DIARY to "Щоденник",
            StringKey.TAB_WEIGHT to "Вага",
            StringKey.TAB_FOODS to "База",
            StringKey.TAB_INSIGHTS to "Поради",
            StringKey.TAB_PROFILE to "Профіль",
            StringKey.HEADER_PLANS_BTN to "Тарифи ⭐",
            StringKey.GUEST_ACCESS_FOREVER to "Безстроково 👑",
            StringKey.GUEST_ACCESS_DAYS_LEFT to "Залишилось дн.:",
            StringKey.GUEST_ACCESS_ACTIVE_CODE to "Активний • Код:",

            StringKey.SAVE to "Зберегти",
            StringKey.CANCEL to "Скасувати",
            StringKey.CLOSE to "Закрити",
            StringKey.DELETE to "Видалити",
            StringKey.EDIT to "Редагувати",
            StringKey.SEARCH to "Пошук",
            StringKey.ADD to "Додати",
            StringKey.COPY to "Копіювати",
            StringKey.SHARE to "Поділитися",
            StringKey.LOADING to "Завантаження...",
            StringKey.ERROR to "Помилка",
            StringKey.SUCCESS to "Успішно",
            StringKey.UNLOCKED to "Доступно",
            StringKey.LOCKED to "Заблоковано",
            StringKey.PRO_REQUIRED to "Потрібен Slim ($20)",
            StringKey.PREMIUM_REQUIRED to "Потрібен Premium ($50)",
            StringKey.ACTIVE_BADGE to "Активний",

            StringKey.LANGUAGE_TITLE to "Мова додатку",
            StringKey.SELECT_LANGUAGE to "Оберіть мову інтерфейсу",

            StringKey.SUBSCRIPTION_TITLE to "Тарифні плани",
            StringKey.CURRENT_PLAN to "Поточний тариф",
            StringKey.PLAN_FREE to "Free (Безкоштовний)",
            StringKey.PLAN_SLIM to "Slim ($20)",
            StringKey.PLAN_PREMIUM to "Premium ($50)",
            StringKey.PLAN_ADMIN to "Адміністратор (VIP)",
            StringKey.FREE_PRICE to "$0",
            StringKey.SLIM_PRICE to "$20",
            StringKey.PREMIUM_PRICE to "$50",
            StringKey.UPGRADE_PLAN to "Покращити тариф",
            StringKey.UNLOCK_ALL to "Відкрити всі функції",
            StringKey.PAYWALL_TITLE to "Всі можливості SlimTrack",
            StringKey.PAYWALL_SUBTITLE to "Оберіть відповідний тариф для швидкого та комфортного схуднення",
            StringKey.PAYWALL_FEATURE_LOCKED_FMT to "Функція доступна в тарифі",
            StringKey.PAYWALL_ALREADY_ACTIVE to "Тариф вже активний ✓",
            StringKey.PAYWALL_BUY_BTN_FMT to "Сплатити",
            StringKey.PAYWALL_SELECT_FREE to "Обрати безкоштовний тариф",
            StringKey.PAYWALL_HAVE_PROMO to "🎁 Є промокод або гостьове посилання?",
            StringKey.PAYWALL_SECURITY_NOTE to "🔒 Миттєва активація та електронна квитанція",
            StringKey.CHOOSE_PLAN to "Обрати тариф",
            StringKey.POPULAR_CHOICE to "Популярний 🔥",
            StringKey.BEST_VALUE to "VIP 👑",

            StringKey.ADMIN_PANEL_TITLE to "Панель адміністратора",
            StringKey.ADMIN_PANEL_SUBTITLE to "Керування доступом, оплатою та оновленнями",
            StringKey.ADMIN_FILE_IMPORT_TITLE to "Імпорт файлу конфігурації (.json)",
            StringKey.ADMIN_FILE_IMPORT_DESC to "Завантажте JSON-файл для оновлення тарифів або бази продуктів",
            StringKey.ADMIN_IMPORT_BUTTON to "Завантажити .JSON",
            StringKey.ADMIN_EXPORT_BUTTON to "Копіювати JSON",
            StringKey.ADMIN_RESET_BUTTON to "Скинути налаштування",
            StringKey.ADMIN_TIER_SIMULATOR to "Тестовий симулятор тарифу",
            StringKey.ADMIN_CONFIG_STATUS to "Статус конфігурації",
            StringKey.ADMIN_CONFIG_SOURCE_DEFAULT to "Вбудована",
            StringKey.ADMIN_CONFIG_SOURCE_FILE to "Із файлу",
            StringKey.ADMIN_CONFIG_UPDATED to "Оновлено",
            StringKey.ADMIN_VIEW_JSON to "Показати JSON",
            StringKey.ADMIN_SUCCESS_IMPORT to "Конфігурацію успішно застосовано!",
            StringKey.ADMIN_ERROR_IMPORT to "Помилка читання файлу конфігурації",
            StringKey.ADMIN_EXTRA_FOODS_IMPORTED to "Імпортовано продуктів",

            StringKey.DIARY_CALORIES_LEFT to "Залишилось",
            StringKey.DIARY_CONSUMED to "З'їдено",
            StringKey.DIARY_BURNED to "Спалено",
            StringKey.DIARY_TARGET to "Норма",
            StringKey.DIARY_PROTEIN to "Білки",
            StringKey.DIARY_FAT to "Жири",
            StringKey.DIARY_CARBS to "Вуглеводи",
            StringKey.DIARY_MEAL_BREAKFAST to "Сніданок",
            StringKey.DIARY_MEAL_LUNCH to "Обід",
            StringKey.DIARY_MEAL_DINNER to "Вечеря",
            StringKey.DIARY_MEAL_SNACKS to "Перекус",
            StringKey.DIARY_ADD_FOOD to "Додати",
            StringKey.DIARY_QUICK_CALORIES to "Швидкі ккал",